# vim: ft=cfg
# Enhanced ncspot Configuration

[settings]
default_keybindings = true
use_nerdfont = true
notify = true
gapless = true
flip_status_indicators = true
shuffle = false
repeat = 'off'

[keybindings]
######################################
# Playback Controls
######################################
"p" = "playpause"
"Enter" = "play"
"s" = "stop"
"r" = "repeat"
"z" = "shuffle"

######################################
# Seek / Track Navigation
######################################
"b" = "seek -5000"
"f" = "seek +5000"
"Shift+b" = "seek -10000"
"Shift+f" = "seek +10000"
"Shift+h" = "previous"
"Shift+l" = "next"

######################################
# Queue Management
######################################
"Space" = "queue"
"Ctrl+s" = "save queue"
"Shift+c" = "clear"  # Dangerous, consider changing this if prone to mistakes
"Shift+q" = "quit"

######################################
# Volume Controls
######################################
"=" = "volup 5"
"-" = "voldown 5"
"Shift+=" = "volup 10"
"Shift+-" = "voldown 10"

######################################
# Movements
######################################
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"g" = "move top"
"Shift+g" = "move bottom"
"." = "move playing"

######################################
# Focus Controls
######################################
"1" = "focus queue"
"2" = "focus library"
"3" = "focus search"
"4" = "focus playlist"

######################################
# Sharing
######################################
"Shift+y" = "share selected"
"y" = "share current"

######################################
# Other
######################################
"?" = "help"
"Ctrl+Shift+r" = "reload"
"Shift+u" = "update"

######################################
# Theme (Enhanced Gruvbox)
######################################
[theme]
background = "#282828"
primary = "#ebdbb2"
secondary = "#928374"
title = "#8ec07c"
playing = "#b8bb26"
playing_bg = "#3c3836"
playing_selected = "#fabd2f"
highlight = "#fabd2f"
highlight_bg = "#3c3836"
error = "#fb4934"
error_bg = "#cc241d"
statusbar_progress = "#458588"
statusbar_bg = "#282828"
statusbar = "#98971a"
cmdline = "#d5c4a1"
cmdline_bg = "#3c3836"
search_match = "#fabd2f"